### ISSUE TITLE
OpenStack terraform provider tests fail with a Cinder volume attach resources

### ISSUE THREAD

**Issue by kayrus** [theopenlab/openlab#571] opened 2020-08-11 09:49 UTC
Thank you for reporting bug!

### Describe the bug

Both Cinder V2 and V3 resources tests fail due to timeout:

* TestAccBlockStorageVolumeAttachV2_basic
* TestAccBlockStorageVolumeAttachV2_timeout
* TestAccBlockStorageVolumeAttachV3_basic
* TestAccBlockStorageVolumeAttachV3_timeout

### Related Job information

https://github.com/terraform-providers/terraform-provider-openstack/pull/1033
https://github.com/terraform-providers/terraform-provider-openstack/pull/1031

**Comment by wangxiyuan** [comment] 2020-08-12 01:57
The job timeout has been update to 6h, please rechek again.

**Comment by kayrus** [comment] 2020-08-12 07:20
@wangxiyuan I don't think that 6h will help. Previously disk attach worked just fine, but now it timeouts.

**Comment by wangxiyuan** [comment] 2020-08-12 07:44
The inner test problem should be debug and fixed at terraform-provider-openstack side first.  OpenLab doesn't know how it works. If its Infra's problem, just let us know then. Do you know the deep reason for the error test?

**Comment by kayrus** [comment] 2020-08-12 07:46
@wangxiyuan I'll try to increase the attach waiting timeout and get back to you.

**Comment by kayrus** [comment] 2020-08-12 13:04
I see the problem. It looks like compute endpoint contains a slash at the end and probably (now, because it somehow worked before) double slashes are not propely recognized.

```
2020-08-12 09:38:33.855250 | ubuntu-bionic | 2020/08/12 09:38:33 [DEBUG] OpenStack Request URL: DELETE http://192.168.0.24/compute/v2.1/servers//os-volume_attachments/1b9c5ce8-6aa1-4083-9656-701f26cf58de
2020-08-12 09:38:33.855403 | ubuntu-bionic | 2020/08/12 09:38:33 [DEBUG] OpenStack Request Headers:
2020-08-12 09:38:33.855483 | ubuntu-bionic | Accept: application/json
2020-08-12 09:38:33.855561 | ubuntu-bionic | Cache-Control: no-cache
2020-08-12 09:38:33.855864 | ubuntu-bionic | User-Agent: HashiCorp Terraform/0.12.7-sdk (+https://www.terraform.io) Terraform Plugin SDK/1.14.0 gophercloud/2.0.0
2020-08-12 09:38:33.855909 | ubuntu-bionic | X-Auth-Token: ***
2020-08-12 09:38:33.904970 | ubuntu-bionic | 2020/08/12 09:38:33 [DEBUG] OpenStack Response Code: 404
2020-08-12 09:38:33.905206 | ubuntu-bionic | 2020/08/12 09:38:33 [DEBUG] OpenStack Response Headers:
2020-08-12 09:38:33.905312 | ubuntu-bionic | Content-Length: 112
2020-08-12 09:38:33.905413 | ubuntu-bionic | Content-Type: application/json
2020-08-12 09:38:33.905521 | ubuntu-bionic | Date: Wed, 12 Aug 2020 09:38:33 GMT
2020-08-12 09:38:33.905653 | ubuntu-bionic | Server: Apache/2.4.29 (Ubuntu)
2020-08-12 09:38:33.905826 | ubuntu-bionic | X-Compute-Request-Id: req-00355c4f-0137-493f-bd44-dd9165202bd6
2020-08-12 09:38:33.906000 | ubuntu-bionic | X-Openstack-Request-Id: req-00355c4f-0137-493f-bd44-dd9165202bd6
2020-08-12 09:38:33.906150 | ubuntu-bionic | 2020/08/12 09:38:33 [DEBUG] OpenStack Response Body: {
2020-08-12 09:38:33.906236 | ubuntu-bionic |   "code": "404 Not Found",
2020-08-12 09:38:33.906502 | ubuntu-bionic |   "message": "The resource could not be found.\u003cbr /\u003e\u003cbr /\u003e\n\n\n",
2020-08-12 09:38:33.906600 | ubuntu-bionic |   "title": "Not Found"
2020-08-12 09:38:33.906629 | ubuntu-bionic | }
```

**Comment by ozerovandrei** [comment] 2020-09-17 08:18
There is what happening in case of `TestAccBlockStorageVolumeAttachV2_timeout`:

1. We're setting `host_name = "devstack"` as an argument to `openstack_blockstorage_volume_attach_v2`: [resource_openstack_blockstorage_volume_attach_v2_test.go#L156](https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/master/openstack/resource_openstack_blockstorage_volume_attach_v2_test.go#L156)

It can be seen in the request body:

```
2020-09-17 07:26:47.438263 | ubuntu-bionic | 2020/09/17 07:26:47 [DEBUG] OpenStack Request Body: {
2020-09-17 07:26:47.438289 | ubuntu-bionic |   "os-attach": {
2020-09-17 07:26:47.438320 | ubuntu-bionic |     "host_name": "devstack",
2020-09-17 07:26:47.438350 | ubuntu-bionic |     "mountpoint": "auto"
2020-09-17 07:26:47.438366 | ubuntu-bionic |   }
2020-09-17 07:26:47.438381 | ubuntu-bionic | }
```

2. We're getting an emtpy `host_name` from the attachment body response inside the volume:

```
2020-09-17 07:26:57.812679 | ubuntu-bionic |     "attachments": [
2020-09-17 07:26:57.812699 | ubuntu-bionic |       {
2020-09-17 07:26:57.812773 | ubuntu-bionic |         "attached_at": "2020-09-17T07:26:48.000000",
2020-09-17 07:26:57.812898 | ubuntu-bionic |         "attachment_id": "1bf4765b-6dbf-4d4b-a296-e6d444a70a16",
2020-09-17 07:26:57.812939 | ubuntu-bionic |         "device": "auto",
2020-09-17 07:26:57.812989 | ubuntu-bionic |         "host_name": null,
2020-09-17 07:26:57.813062 | ubuntu-bionic |         "id": "873d4f20-a728-454a-9aaa-abe6a8c25143",
2020-09-17 07:26:57.813099 | ubuntu-bionic |         "server_id": null,
2020-09-17 07:26:57.813168 | ubuntu-bionic |         "volume_id": "873d4f20-a728-454a-9aaa-abe6a8c25143"
2020-09-17 07:26:57.813194 | ubuntu-bionic |       }
2020-09-17 07:26:57.813242 | ubuntu-bionic |     ],
```

And we can't find the needed attachment because of the empty `host_name` since we do the following in [resource_openstack_blockstorage_volume_attach_v2.go#L256](https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/master/openstack/resource_openstack_blockstorage_volume_attach_v2.go#L256):

```go
	// Search for the attachmentId
	var attachmentId string
	hostName := d.Get("host_name").(string)
	for _, attachment := range volume.Attachments {
		if hostName != "" && hostName == attachment.HostName {
			attachmentId = attachment.AttachmentID
		}
	}

	if attachmentId == "" {
		return fmt.Errorf(
			"Unable to determine attachment ID for openstack_blockstorage_volume_attach_v2 volume %s.", volumeId)
	}
```

3. And test is failing with the error from the code above:

```
2020-09-17 07:26:57.815386 | ubuntu-bionic | 2020/09/17 07:26:57 [DEBUG] openstack_blockstorage_volume_attach_v2.va_1: apply errored, but we're indicating that via the Error pointer rather than returning it: Unable to determine attachment ID for openstack_blockstorage_volume_attach_v2 volume 873d4f20-a728-454a-9aaa-abe6a8c25143.
2020-09-17 07:26:57.815559 | ubuntu-bionic | 2020/09/17 07:26:57 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: Unable to determine attachment ID for openstack_blockstorage_volume_attach_v2 volume 873d4f20-a728-454a-9aaa-abe6a8c25143.
2020-09-17 07:26:57.815728 | ubuntu-bionic | 2020/09/17 07:26:57 [ERROR] <root>: eval: *terraform.EvalSequence, err: Unable to determine attachment ID for openstack_blockstorage_volume_attach_v2 volume 873d4f20-a728-454a-9aaa-abe6a8c25143.
```

All logs are from [68499c1e3dd34a52aeb686467e4c713e?logfile=console.log](https://status.openlabtesting.org/stream/68499c1e3dd34a52aeb686467e4c713e?logfile=console.log) that was triggered by [terraform-provider-openstack/pull/1067](https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1067)

@wangxiyuan could you please check why the `host_name` of the new attachment is empty despite the fact that we set it explicitly?

**Comment by ozerovandrei** [comment] 2020-09-17 08:35
Follow-up to my last comment.

I guess this is happening because of those patches:

https://review.opendev.org/#/c/726751/
https://github.com/openstack/cinder/commit/8bf454b0b5c7b77bdde8fe8a98d5225957e9c912

**Comment by ozerovandrei** [comment] 2020-09-17 08:40
I guess we can add `testAccPreCheckAdminOnly` condition to attachment tests.
And then they will be run only after we will decide what to do in https://github.com/theopenlab/openlab/issues/365.

**Comment by wangxiyuan** [comment] 2020-09-17 09:33
@ozerovandrei I'm away from OpenStack almost 2 years. Sorry that I don't have enough time to debug the error. (Since the problem is not related to OpenLab  infrastructure).

 But How do you think if you can login to the VM to debug by yourself? I can add a temp admin user and pause the test in the job defination code, then you guys from terraform can login and do what ever you want.

**Comment by ozerovandrei** [comment] 2020-09-18 06:45
@wangxiyuan thanks but in this particular case it's not needed since host information should be hidden from the regular user: https://review.opendev.org/#/c/726751/.

I guess we can close this issue.

We will enable those tests for admin only and update documentation for those resources in https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1068.

**Comment by wangxiyuan** [comment] 2020-09-18 07:09
cool. Feel free to close the issue if the problem is solved.

**Closed** 2020-09-18 08:48 UTC
Labels: bug
